/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kuis;
<<<<<<< HEAD
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class RecordFrame extends javax.swing.JFrame {
    public static KalkulatorClass dKalkulator = new KalkulatorClass();
=======

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hokyt
 */

public class RecordFrame extends javax.swing.JFrame {
    public static KalkulatorClass mHistoryData = new KalkulatorClass();
>>>>>>> 068612d5efd19c38dbefc7487975dc5119431d50
    
    DefaultTableModel model;
    /**
     * Creates new form RecordFrame
     */
    public RecordFrame() {
        initComponents();
<<<<<<< HEAD
        dKalkulator = Kalkulator.dataKalkulator;
        
        String[]NamaKolom = {"Angka1","Angka2","Operator","Hasil"};
        Object [][] objekKalkulator = new Object[dKalkulator.getData().size()][4];
        
        int index=0;
        for (int i = 0; i < dKalkulator.getData().size() ; i++) {
            Record model = dKalkulator.getData().get(i);
            String [] array = {model.getAngka1(),
                                model.getAngka2(),
                                model.getOperator(),
                                model.getHasil()};
            objekKalkulator[i] = array;
        }
        model = new DefaultTableModel(objekKalkulator, NamaKolom);
        jTable1.setModel(model);
=======
        mHistoryData = Kalkulator.mHistoryDataKalklator;
        
        String[] NamaKolom = {"Angka 1", "Angka 2", "Operator", "Hasil"};
        Object[][] objekKalkulator = (Object[][]) new Object[mHistoryData.getData().size()];
        
        int index = 0;
        for (int ii = 0; ii < mHistoryData.getData().size(); ii++) {
            Record model = mHistoryData.getData().get(ii);
            String[] array = {model.getAngka1(), model.getAngka2(), model.getOperator(), model.getHasil()};
            objekKalkulator[ii] = array;
        }
        
>>>>>>> 068612d5efd19c38dbefc7487975dc5119431d50
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
<<<<<<< HEAD
        jTable1 = new javax.swing.JTable();
        jTableData = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
=======
        jTableData = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableData.setModel(new javax.swing.table.DefaultTableModel(
>>>>>>> 068612d5efd19c38dbefc7487975dc5119431d50
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
<<<<<<< HEAD
        jScrollPane1.setViewportView(jTable1);

        jTableData.setText("Back");
=======
        jScrollPane1.setViewportView(jTableData);

        jButton1.setText("jButton1");
>>>>>>> 068612d5efd19c38dbefc7487975dc5119431d50

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTableData)
                .addGap(37, 37, 37))
=======
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
>>>>>>> 068612d5efd19c38dbefc7487975dc5119431d50
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jTableData)
                .addContainerGap(74, Short.MAX_VALUE))
=======
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(79, Short.MAX_VALUE))
>>>>>>> 068612d5efd19c38dbefc7487975dc5119431d50
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jTableData;
    // End of variables declaration//GEN-END:variables

=======
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableData;
    // End of variables declaration//GEN-END:variables
>>>>>>> 068612d5efd19c38dbefc7487975dc5119431d50
}
